# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f1f029f1565eda4f2c95fc79a8964c286760dfa87bd251f5b7c29a252dfcd7ba3de7a2b073de29c14df5c2a52d83e560bb5046ffbea6febf96f3a0890b6c02e

test:
  secret_key_base: af75c346297a599bf2f8ac925a43613491502119a57f78cfb0c6725bd4fb988d53a8c5a61d01f9a5116e24ff6b4eb1881626c7d294acda2b1ec6b94d57f2cae9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
